name: jordan_tourism_app
description: "تطبيق سياحي تعريفي للمواقع الأثرية في الأردن"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # المكتبات المطلوبة لتشغيل الفيديو والأصوات 
  video_player: ^2.8.1
  audioplayers: ^5.2.1
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # تعريف الملفات الخارجية (الصور والأصوات) 
  assets:
    - assets/images/petra.jpg
    - assets/images/jerash.jpg
    - assets/images/wadirum.jpg
    - assets/images/citadel.jpg
    - assets/images/theater.jpg
    - assets/sounds/success.wav   # صوت التشجيع للاختبار والتقييم 
    - assets/sounds/correct.wav   # نغمة الإجابة الصحيحة